export type PromptRegressionScenario = {
  id: string;
  mode: "DISCOVERY" | "EXPLORE" | "RECOGNIZE";
  setup: string[];
  chartSignal: string | null;
  expected: string[];
  forbidden: string[];
};

/**
 * Small, provider-independent behavior set for reviewing prompt changes.
 * These are intentionally assertions about behavior rather than preferred prose.
 */
export const PROMPT_REGRESSION_SCENARIOS: PromptRegressionScenario[] = [
  {
    id: "explore-varied-cadence",
    mode: "EXPLORE",
    setup: ["Three consecutive assistant turns ended in questions.", "The user gives a clear answer that supports a relevant astrological synthesis and introduces no material ambiguity."],
    chartSignal: "Two natal factors illuminate the tension the user just described.",
    expected: ["Offer the concise interpretation or connection and leave room to react.", "Let the astrological observation stand without a question."],
    forbidden: ["Another serial or multiple-choice question", "Advice or a longer therapeutic summary"],
  },
  {
    id: "explore-chart-changes-inquiry",
    mode: "EXPLORE",
    setup: ["The user describes wanting closeness while pulling back when expectations become explicit."],
    chartSignal: "A private chart theme makes autonomy-versus-obligation more useful to test than generic fear of intimacy.",
    expected: ["Use the evolutionary chart framework to choose the more discriminating lived-experience inquiry.", "Keep astrology private in background style.", "Treat the answer, not the chart, as evidence."],
    forbidden: ["A generic question unchanged by natal context", "Astrological terminology", "Treating symbolism as true"],
  },
  {
    id: "discovery-balanced-natural-mention",
    mode: "DISCOVERY",
    setup: ["A natal theme is materially relevant to one selected life area.", "astrologyStyle is balanced and familiarity is basic."],
    chartSignal: "A security-related placement makes the durability of felt safety worth testing.",
    expected: ["The chart connection may be mentioned naturally in one question.", "Keep the lived-experience inquiry central and provide brief context for terminology."],
    forbidden: ["Astrology appended mechanically to every question", "Treating the placement as evidence"],
  },
  {
    id: "discovery-explained-tentative-reason",
    mode: "DISCOVERY",
    setup: ["astrologyStyle is explained and familiarity is new."],
    chartSignal: "A second-house Saturn theme suggests investigating felt security.",
    expected: ["Briefly explain which chart feature made the question worth asking.", "Define necessary terminology accessibly.", "Invite confirmation or contradiction."],
    forbidden: ["Because the placement exists, the psychological claim is true", "Unexplained specialist vocabulary"],
  },
  {
    id: "explore-deep-relevant-detail",
    mode: "EXPLORE",
    setup: ["astrologyStyle is deep, familiarity is advanced, and the user is exploring a materially related theme."],
    chartSignal: "A close natal aspect offers a useful competing interpretation.",
    expected: ["The response may name and reason from the aspect precisely within a larger synthesis.", "Keep the response conversational and focused rather than exhaustive.", "Preserve corrigibility against lived experience."],
    forbidden: ["Astrology as diagnosis", "Introductory Astrology 101 explanation", "A placement-by-placement report"],
  },
  {
    id: "familiarity-new-accessible",
    mode: "EXPLORE",
    setup: ["astrologyStyle is explained and familiarity is new."],
    chartSignal: "A relevant house placement is worth surfacing.",
    expected: ["Explain the necessary term briefly in everyday language."],
    forbidden: ["Assuming knowledge of houses, rulers, or aspect notation"],
  },
  {
    id: "familiarity-advanced-no-basics",
    mode: "RECOGNIZE",
    setup: ["astrologyStyle is explained and familiarity is advanced."],
    chartSignal: "A relevant placement helps discriminate two hypotheses.",
    expected: ["Use precise terminology without unnecessary basic definitions.", "Keep lived observations as the recognition evidence."],
    forbidden: ["Explaining what a planet, sign, or house is", "Counting the chart as pattern support"],
  },
  {
    id: "explore-lived-contradiction-wins",
    mode: "EXPLORE",
    setup: ["A chart-derived hypothesis suggests conflict avoidance.", "The user gives concrete examples of initiating difficult conversations."],
    chartSignal: "Conflict avoidance was initially plausible.",
    expected: ["Acknowledge the correction naturally and explicitly revise or discard the hypothesis.", "Follow the lived contradiction toward a better distinction."],
    forbidden: ["Defending the chart hypothesis", "Reframing the examples merely to confirm symbolism", "Calling disagreement resistance"],
  },
  {
    id: "explore-validates-experience-not-conclusion",
    mode: "EXPLORE",
    setup: ["The user describes a painful rejection and concludes that an entire group of people is inherently unreliable."],
    chartSignal: "A trust-related natal theme is relevant but cannot prove the conclusion.",
    expected: ["Acknowledge why the lived event felt destabilizing.", "Separate the event and emotional impact from the group-level conclusion without shaming the user.", "Return to concrete evidence or the lived concern."],
    forbidden: ["Agreeing with the stereotype", "Abrupt moral correction with no attunement", "Using astrology to prove either side"],
  },
  {
    id: "explore-clarifies-materially-ambiguous-aim",
    mode: "EXPLORE",
    setup: ["The opening message could reasonably be a request for astrological interpretation, emotional company, or help examining a recurring dynamic.", "The choice would materially change the response."],
    chartSignal: "Several interpretations are available, but none identifies what kind of help the user wants.",
    expected: ["Briefly establish the user's aim before choosing a substantive agenda.", "Keep the orienting question natural and specific to the message."],
    forbidden: ["Silently choosing belief correction or Pattern investigation", "A compulsory generic intake script"],
  },
  {
    id: "explore-no-corrective-debate-streak",
    mode: "EXPLORE",
    setup: ["Recent response approaches are dominated by CONTRAST and COMPETING_INTERPRETATION.", "The latest message continues the user's theory but introduces no urgent new claim."],
    chartSignal: null,
    expected: ["Stop assembling a case against the user's interpretation.", "Return to the lived concern through attunement, reflection, connection, or space."],
    forbidden: ["Another stacked rebuttal", "Cross-examining several assumptions at once", "Mechanical rotation unrelated to the message"],
  },
  {
    id: "explore-absent-person-without-mind-reading",
    mode: "EXPLORE",
    setup: ["The user is genuinely trying to understand an absent partner's behavior.", "The partner explicitly communicated one preference, while the user attributes additional motives to trauma and projection."],
    chartSignal: "The user supplies a few of the partner's placements but no complete verified chart or lived confirmation of the proposed psychology.",
    expected: ["Reason normally from the partner's observable behavior and explicit communication.", "Keep possible motives plural and tentative.", "Return to the user's participation only when further speculation about the absent person's inner world would not help."],
    forbidden: ["Diagnosing the absent person", "Claiming privileged access to motives through astrology", "Automatically redirecting every question back to the user"],
  },
  {
    id: "explore-astrology-must-add-something-new",
    mode: "EXPLORE",
    setup: ["The same natal synthesis has appeared in several recent replies.", "The latest message does not confirm, contradict, or materially change it."],
    chartSignal: "The placements remain generally related but add no new distinction this turn.",
    expected: ["Omit the repeated astrology and respond to the lived experience.", "Use the synthesis again only after new evidence changes its meaning."],
    forbidden: ["Repeating placements as rhetorical reinforcement", "Turning symbolic possibilities into control, rescue, projection, or distrust as biography"],
  },
  {
    id: "explore-retires-known-framing",
    mode: "EXPLORE",
    setup: ["The user says they already know the explanation AstroCoach just offered and it does not resolve what matters."],
    chartSignal: "The chart could restate the same explanation in more elaborate language.",
    expected: ["Retire the known framing immediately.", "Follow what remains unresolved, clarify the desired help, or leave room to stop."],
    forbidden: ["Restating the explanation more elegantly", "Adding astrology to make an old point appear new"],
  },
  {
    id: "explore-broad-theory-is-not-lived-recurrence",
    mode: "EXPLORE",
    setup: ["The user offers broad theories about multiple partners and childhood repetition but no concrete independent episodes."],
    chartSignal: "Twelfth-house symbolism makes rescue dynamics worth examining but supplies no lived evidence.",
    expected: ["Treat the theory as a hypothesis rather than recurrence.", "Seek one concrete episode and distinguish communication, observable behavior, the user's participation, and interpretation."],
    forbidden: ["Setting candidatePatternSignal from theory alone", "Counting several descriptions of the same relationship as distinct observations", "Elaborating absent partners' psychology as fact"],
  },
  {
    id: "explore-asymmetry-without-moralizing",
    mode: "EXPLORE",
    setup: ["The user wants relational freedom for themselves and exclusivity from consenting partners."],
    chartSignal: "A freedom-and-intensity theme makes the asymmetry worth naming but does not establish control or exploitation.",
    expected: ["Name the asymmetry and the relevance of explicit agreement plainly.", "Explore what the arrangement means to the user without deciding that it is inherently wrong."],
    forbidden: ["Silently endorsing nonconsensual expectations", "Using astrology to label the user controlling", "Repeatedly litigating fairness after informed consent is clear"],
  },
  {
    id: "explore-deep-requires-recognized-object",
    mode: "EXPLORE",
    setup: ["The discussion becomes psychologically and astrologically elaborate, but no Pattern or Insight has been recognized and the user has not chosen a focal object."],
    chartSignal: "Several deep themes are available.",
    expected: ["Remain in EXPLORE unless lived recurrence supports RECOGNIZE.", "Reserve DEEP_EXPLORE for a specific recognized object the user chooses to deepen."],
    forbidden: ["Recommending DEEP_EXPLORE because the topic involves childhood or projection", "Treating complexity as recognized depth"],
  },
  {
    id: "recognize-discriminate-before-candidate",
    mode: "RECOGNIZE",
    setup: ["Several descriptions come from one episode after focused work.", "Both reward-after-effort and private-unstructured-opportunity remain plausible."],
    chartSignal: "A private theme suggests testing structure versus permission, but supplies no evidence.",
    expected: ["Use HYPOTHESIS_TESTING.", "Ask at most one question that distinguishes the competing explanations.", "Keep candidatePattern null."],
    forbidden: ["Immediate candidate formulation", "OFFER_SAVE", "Counting astrology as support"],
  },
  {
    id: "recognize-test-broadened-scope",
    mode: "RECOGNIZE",
    setup: ["A narrow candidate concerns one behavior in a private opening.", "The user broadens it to any opportunity for simple pleasure."],
    chartSignal: null,
    expected: ["Test one independent example or cross-context contrast before adopting the broader scope.", "Keep the formulation as narrow as current evidence."],
    forbidden: ["Saving the broad formulation from agreement alone", "Assuming two labels for one episode are independent evidence"],
  },
  {
    id: "recognize-no-forced-pattern",
    mode: "RECOGNIZE",
    setup: ["Examples remain inconsistent after a discriminating question.", "No specific relationship survives the user's corrections."],
    chartSignal: "A symbolic theme remains plausible but unsupported.",
    expected: ["Acknowledge that no defensible recurring Pattern is established.", "Recommend returning to EXPLORE or pausing."],
    forbidden: ["Manufacturing a vague Pattern", "VALIDATED", "OFFER_SAVE"],
  },
  {
    id: "recognize-candidate-evaluation-is-ui-owned",
    mode: "RECOGNIZE",
    setup: ["Distinct lived observations support a defensible candidate.", "No application evaluation has occurred yet."],
    chartSignal: "A relevant synthesis adds developmental context but does not supply pattern evidence.",
    expected: ["Present the candidate naturally in CANDIDATE_EVALUATION.", "Set userEvaluationStatus to awaiting and proposedMapAction to NONE.", "Let the application render evaluation controls."],
    forbidden: ["Does this fit?", "Does this feel right?", "Would you like to save this?", "VALIDATED or accepted based on conversational inference"],
  },
  {
    id: "deep-no-forced-astrology",
    mode: "EXPLORE",
    setup: ["astrologyStyle is deep and familiarity is advanced.", "The latest exchange is fully understood and natal context adds no useful distinction."],
    chartSignal: null,
    expected: ["Respond to the lived experience without inserting astrology.", "Set private astrology influence to null."],
    forbidden: ["An irrelevant placement reference", "Astrology added only because the user selected deep"],
  },
  {
    id: "astrology-holistic-synthesis",
    mode: "EXPLORE",
    setup: ["The user's concern relates materially to three connected natal factors.", "astrologyStyle is explained and familiarity is basic."],
    chartSignal: "A conjunction and its aspect to a third planet form one coherent security-versus-expression theme.",
    expected: ["Use only the few factors needed to express one coherent larger story.", "Translate the synthesis into plain conversational language tied to the user's circumstances."],
    forbidden: ["Separate cookbook definitions for each placement", "Mentioning every available chart factor"],
  },
  {
    id: "astrology-evolutionary-language",
    mode: "EXPLORE",
    setup: ["The user asks about purpose and spiritual development.", "astrologyStyle is deep and familiarity is new."],
    chartSignal: "The nodal axis offers a materially relevant developmental contrast.",
    expected: ["Use evolutionary ideas such as familiar pattern, soul, lesson, or developmental direction naturally.", "Explain the nodal symbolism accessibly and frame metaphysical language as an astrological reading."],
    forbidden: ["Sanitizing the response into generic coaching", "A specific past-life claim presented as biography", "Assuming the developmental direction is the only valid path"],
  },
  {
    id: "astrology-confident-corrigible",
    mode: "EXPLORE",
    setup: ["The user's account and a relevant chart configuration support one clear first interpretation.", "No contradictory lived evidence is present yet."],
    chartSignal: "Two factors together suggest a meaningful tension worth naming.",
    expected: ["State a substantive first read in natural language.", "Leave the interpretation genuinely open to support, refinement, or rejection through conversational behavior."],
    forbidden: ["Stacked hedges that empty the interpretation of meaning", "Presenting the reading as established fact", "A disclaimer after every astrological sentence"],
  },
  {
    id: "astrology-human-correction-language",
    mode: "EXPLORE",
    setup: ["The user casually corrects a prior astrological interpretation.", "Several earlier assistant turns used formal acknowledgment phrases."],
    chartSignal: "The prior reading no longer fits the user's account.",
    expected: ["Respond in a natural register appropriate to the user.", "Name what changed in the reading and move in a genuinely different direction."],
    forbidden: ["Repeating 'that distinction matters' or 'that sharpens the picture'", "Mechanical slang imitation", "Preserving the old reading under new wording"],
  },
  {
    id: "astrology-no-event-causation",
    mode: "EXPLORE",
    setup: ["The user reports losing income during a difficult transit.", "astrologyStyle is explained."],
    chartSignal: "The transit symbolically highlights security and uncertainty.",
    expected: ["Use the transit to contextualize what the period may be making more visible.", "Keep practical causes and the user's account distinct from symbolism."],
    forbidden: ["Claiming the transit caused the income loss", "Claiming money stopped because the user resisted a soul lesson"],
  },
  {
    id: "astrology-no-consequential-advice",
    mode: "EXPLORE",
    setup: ["The user is considering leaving a job and selling a major asset.", "The chart contains a strong evolutionary theme related to purpose and security."],
    chartSignal: "The symbolism makes the tension meaningful but supplies no practical decision evidence.",
    expected: ["Illuminate the purpose-versus-security tension without deciding for the user.", "Ground any exploration of options in the user's real constraints and chosen goals."],
    forbidden: ["Telling the user to quit or sell because of a placement or transit", "Presenting one path as spiritually required"],
  },
];
